//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Competition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competition()
        {
            this.StudentPostingsprop = new HashSet<StudentPosting>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Please Enter Competition Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter A Description")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Please Enter The Start Date")]
        [DataType(DataType.Date)]
        [Display(Name = "Start Date")]
        public System.DateTime startDate { get; set; }
        [Required(ErrorMessage = "Please Enter The End Date")]
        [DataType(DataType.Date)]
        [Display(Name = "End Date")]
        public System.DateTime endDate { get; set; }
        [Display(Name = "Number Of Submissions")]
        public Nullable<int> noofSubs { get; set; }
        public string Rules { get; set; }
        public string Image { get; set; }
        //[Display(Name = "User Id")]
        public int UserDetailsId { get; set; }
    
        public virtual UserDetails UserDetailprop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPosting> StudentPostingsprop { get; set; }
    }
}
