//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class StudentPosting
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please Enter Post Name")]
        public string Name { get; set; }
        public string Remarks { get; set; }
        [Required(ErrorMessage = "Please Enter A Rating From Needs Work & Good To Best")]
        public string Rating { get; set; }
        [Display(Name = "Competition Name")]
        public string compName { get; set; }
        [Display(Name = "Award Winner")]
        public bool awardWin { get; set; }
        [Display(Name = "Number Of Awards")]
        public Nullable<int> noofAwards { get; set; }
        [Required(ErrorMessage = "Please Select A Picture")]
        public string Image { get; set; }
        public int UserDetailsId { get; set; }
        public int CompetitionId { get; set; }
    
        public virtual UserDetails UserDetailprop { get; set; }
        public virtual Competition Competitionprop { get; set; }
    }
}
