//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetails()
        {
            this.Competitionsprop = new HashSet<Competition>();
            this.StudentPostingsprop = new HashSet<StudentPosting>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Please Enter Your Name")]
        public string Name { get; set; }
        [Display(Name = "Full Name")]
        public string fullName { get; set; }
        [Display(Name = "Father Name")]
        public string fatherName { get; set; }
        [Required(ErrorMessage = "Please Enter A Valid Email")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email Is Not Valid.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Subject { get; set; }
        public string Contact { get; set; }
        [Display(Name = "Date of Employment / Admission")]
        [Required(ErrorMessage = "Please Enter The Date Of Your Employment / Admission")]
        [DataType(DataType.Date)]
        public System.DateTime dateofJoin { get; set; }
        public bool Admin { get; set; }
        public bool Staff { get; set; }
        public bool Student { get; set; }
        public bool Manager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competition> Competitionsprop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPosting> StudentPostingsprop { get; set; }
    }
}
